workflows:
  android-workflow:
    name: SiteNative Android aab
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "fr.repono.nuage"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build AAB with Flutter
        script: |
          cd . && flutter build appbundle --release --build-name=1.0.0 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://demo.flangapp.com/backend/api/observe/notice/7aa9c16f-ffd2-eda1-8e6f-9e76937d29a8